// Code generated by protoc-gen-go. DO NOT EDIT.
// source: content.proto

package content

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Content struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                string   `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_61cc9617ce0cf609, []int{0}
}

func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Content) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Content) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Content) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GetContentRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContentRequest) Reset()         { *m = GetContentRequest{} }
func (m *GetContentRequest) String() string { return proto.CompactTextString(m) }
func (*GetContentRequest) ProtoMessage()    {}
func (*GetContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61cc9617ce0cf609, []int{1}
}

func (m *GetContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContentRequest.Unmarshal(m, b)
}
func (m *GetContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContentRequest.Marshal(b, m, deterministic)
}
func (m *GetContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContentRequest.Merge(m, src)
}
func (m *GetContentRequest) XXX_Size() int {
	return xxx_messageInfo_GetContentRequest.Size(m)
}
func (m *GetContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContentRequest proto.InternalMessageInfo

func (m *GetContentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetContentResponse struct {
	Content              *Content `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContentResponse) Reset()         { *m = GetContentResponse{} }
func (m *GetContentResponse) String() string { return proto.CompactTextString(m) }
func (*GetContentResponse) ProtoMessage()    {}
func (*GetContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61cc9617ce0cf609, []int{2}
}

func (m *GetContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContentResponse.Unmarshal(m, b)
}
func (m *GetContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContentResponse.Marshal(b, m, deterministic)
}
func (m *GetContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContentResponse.Merge(m, src)
}
func (m *GetContentResponse) XXX_Size() int {
	return xxx_messageInfo_GetContentResponse.Size(m)
}
func (m *GetContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetContentResponse proto.InternalMessageInfo

func (m *GetContentResponse) GetContent() *Content {
	if m != nil {
		return m.Content
	}
	return nil
}

type GetContentsRequest struct {
	AfterId              string   `protobuf:"bytes,1,opt,name=after_id,json=afterId,proto3" json:"after_id,omitempty"`
	BeforeId             string   `protobuf:"bytes,2,opt,name=before_id,json=beforeId,proto3" json:"before_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContentsRequest) Reset()         { *m = GetContentsRequest{} }
func (m *GetContentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetContentsRequest) ProtoMessage()    {}
func (*GetContentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61cc9617ce0cf609, []int{3}
}

func (m *GetContentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContentsRequest.Unmarshal(m, b)
}
func (m *GetContentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContentsRequest.Marshal(b, m, deterministic)
}
func (m *GetContentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContentsRequest.Merge(m, src)
}
func (m *GetContentsRequest) XXX_Size() int {
	return xxx_messageInfo_GetContentsRequest.Size(m)
}
func (m *GetContentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContentsRequest proto.InternalMessageInfo

func (m *GetContentsRequest) GetAfterId() string {
	if m != nil {
		return m.AfterId
	}
	return ""
}

func (m *GetContentsRequest) GetBeforeId() string {
	if m != nil {
		return m.BeforeId
	}
	return ""
}

type GetContentsResponse struct {
	Contents             []*Content `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetContentsResponse) Reset()         { *m = GetContentsResponse{} }
func (m *GetContentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetContentsResponse) ProtoMessage()    {}
func (*GetContentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61cc9617ce0cf609, []int{4}
}

func (m *GetContentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContentsResponse.Unmarshal(m, b)
}
func (m *GetContentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContentsResponse.Marshal(b, m, deterministic)
}
func (m *GetContentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContentsResponse.Merge(m, src)
}
func (m *GetContentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetContentsResponse.Size(m)
}
func (m *GetContentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetContentsResponse proto.InternalMessageInfo

func (m *GetContentsResponse) GetContents() []*Content {
	if m != nil {
		return m.Contents
	}
	return nil
}

func init() {
	proto.RegisterType((*Content)(nil), "Content")
	proto.RegisterType((*GetContentRequest)(nil), "GetContentRequest")
	proto.RegisterType((*GetContentResponse)(nil), "GetContentResponse")
	proto.RegisterType((*GetContentsRequest)(nil), "GetContentsRequest")
	proto.RegisterType((*GetContentsResponse)(nil), "GetContentsResponse")
}

func init() { proto.RegisterFile("content.proto", fileDescriptor_61cc9617ce0cf609) }

var fileDescriptor_61cc9617ce0cf609 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x55, 0xd2, 0x42, 0xd2, 0x8b, 0xa8, 0xc4, 0xb5, 0x83, 0x29, 0x4b, 0x64, 0x18, 0x98, 0x3c,
	0x14, 0x21, 0x55, 0x62, 0x64, 0x40, 0x95, 0x98, 0xca, 0x07, 0xa0, 0x36, 0xbe, 0x4a, 0x1e, 0xb0,
	0x83, 0x6d, 0xd8, 0xf9, 0x73, 0x54, 0xc7, 0x29, 0xae, 0x9a, 0x2d, 0xf7, 0xde, 0xcb, 0xbd, 0xf7,
	0xce, 0x70, 0xd5, 0x18, 0xed, 0x49, 0x7b, 0xd1, 0x5a, 0xe3, 0x0d, 0x27, 0x28, 0x5e, 0x3a, 0x00,
	0xa7, 0x90, 0x2b, 0xc9, 0xb2, 0x3a, 0x7b, 0x98, 0x6c, 0x72, 0x25, 0x11, 0x61, 0xac, 0xb7, 0x9f,
	0xc4, 0xf2, 0x80, 0x84, 0x6f, 0x9c, 0xc3, 0x45, 0x6b, 0x55, 0x43, 0x6c, 0x14, 0xc0, 0x6e, 0xc0,
	0x1a, 0x2a, 0x49, 0xae, 0xb1, 0xaa, 0xf5, 0xca, 0x68, 0x36, 0x0e, 0x5c, 0x0a, 0xf1, 0x3b, 0xb8,
	0x7e, 0x25, 0x1f, 0x9d, 0x36, 0xf4, 0xf5, 0x4d, 0xee, 0xcc, 0x90, 0xaf, 0x00, 0x53, 0x91, 0x6b,
	0x8d, 0x76, 0x84, 0x1c, 0x8a, 0x18, 0x39, 0x48, 0xab, 0x65, 0x29, 0x7a, 0x49, 0x4f, 0xf0, 0xb7,
	0xf4, 0x4f, 0xd7, 0xef, 0xbf, 0x81, 0x72, 0xbb, 0xf7, 0x64, 0x3f, 0x8e, 0x2e, 0x45, 0x98, 0xd7,
	0x12, 0x6f, 0x61, 0xb2, 0xa3, 0xbd, 0xb1, 0x74, 0xe0, 0xba, 0x82, 0x65, 0x07, 0xac, 0x25, 0x7f,
	0x86, 0xd9, 0xc9, 0xb6, 0x18, 0xe4, 0x1e, 0xca, 0xe8, 0xe7, 0x58, 0x56, 0x8f, 0x4e, 0x92, 0x1c,
	0x99, 0xe5, 0x6f, 0x06, 0xd3, 0x88, 0xbe, 0x93, 0xfd, 0x39, 0x9c, 0xe7, 0x09, 0xe0, 0x7f, 0x1f,
	0xa2, 0x38, 0xbb, 0xc4, 0x62, 0x26, 0x06, 0x8a, 0xaf, 0xa0, 0x4a, 0x62, 0x60, 0xaa, 0xe9, 0x2b,
	0x2e, 0xe6, 0x62, 0x20, 0xe9, 0xee, 0x32, 0xbc, 0xed, 0xe3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x10, 0xaa, 0x40, 0xb4, 0xec, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContentServiceClient is the client API for ContentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContentServiceClient interface {
	GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error)
	GetContents(ctx context.Context, in *GetContentsRequest, opts ...grpc.CallOption) (*GetContentsResponse, error)
}

type contentServiceClient struct {
	cc *grpc.ClientConn
}

func NewContentServiceClient(cc *grpc.ClientConn) ContentServiceClient {
	return &contentServiceClient{cc}
}

func (c *contentServiceClient) GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error) {
	out := new(GetContentResponse)
	err := c.cc.Invoke(ctx, "/ContentService/GetContent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentServiceClient) GetContents(ctx context.Context, in *GetContentsRequest, opts ...grpc.CallOption) (*GetContentsResponse, error) {
	out := new(GetContentsResponse)
	err := c.cc.Invoke(ctx, "/ContentService/GetContents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentServiceServer is the server API for ContentService service.
type ContentServiceServer interface {
	GetContent(context.Context, *GetContentRequest) (*GetContentResponse, error)
	GetContents(context.Context, *GetContentsRequest) (*GetContentsResponse, error)
}

// UnimplementedContentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedContentServiceServer struct {
}

func (*UnimplementedContentServiceServer) GetContent(ctx context.Context, req *GetContentRequest) (*GetContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContent not implemented")
}
func (*UnimplementedContentServiceServer) GetContents(ctx context.Context, req *GetContentsRequest) (*GetContentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContents not implemented")
}

func RegisterContentServiceServer(s *grpc.Server, srv ContentServiceServer) {
	s.RegisterService(&_ContentService_serviceDesc, srv)
}

func _ContentService_GetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentService/GetContent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetContent(ctx, req.(*GetContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentService_GetContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServiceServer).GetContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentService/GetContents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServiceServer).GetContents(ctx, req.(*GetContentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ContentService",
	HandlerType: (*ContentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContent",
			Handler:    _ContentService_GetContent_Handler,
		},
		{
			MethodName: "GetContents",
			Handler:    _ContentService_GetContents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "content.proto",
}
